package com.templeregistry.entity.timeline;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * Immutable audit record of every significant event in a temple's lifecycle.
 *
 * Design rules (same as WorkflowTransition):
 *   - Does NOT extend BaseEntity — immutable once written, never updated.
 *   - No @SQLDelete / @SQLRestriction — this table is never soft-deleted.
 *   - source_transition_id UNIQUE index provides idempotency guard at DB level.
 *   - Append-only: application code must never UPDATE or DELETE rows from this table.
 */
@Entity
@Table(
    name = "temple_timeline_events",
    indexes = {
        @Index(name = "idx_timeline_temple_occurred", columnList = "temple_id, occurred_at DESC"),
        @Index(name = "idx_timeline_event_type",      columnList = "temple_id, event_type"),
        @Index(name = "idx_timeline_source_transition", columnList = "source_transition_id")
    }
)
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TempleTimelineEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ─── Scoping ──────────────────────────────────────────────────────────────

    @Column(name = "temple_id", nullable = false, updatable = false)
    private Long templeId;

    // ─── Event Classification ─────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 40, updatable = false)
    private TimelineEventType eventType;

    @Enumerated(EnumType.STRING)
    @Column(name = "event_code", nullable = false, length = 64, updatable = false)
    private TimelineEventCode eventCode;

    /** e.g. TEMPLE_PROFILE, DECLARATION, TRUST, BOARD_MEMBER, EMPLOYEE, CONTRACTOR, DOCUMENT */
    @Column(name = "module_name", length = 40, updatable = false)
    private String moduleName;

    /** Human-readable name of the affected entity, e.g. "Trust Deed.pdf". */
    @Column(name = "entity_name", length = 255, updatable = false)
    private String entityName;

    // ─── Display ──────────────────────────────────────────────────────────────

    @Column(name = "title", nullable = false, length = 255, updatable = false)
    private String title;

    @Column(name = "description", columnDefinition = "TEXT", updatable = false)
    private String description;

    /** Optional JSON blob for module-specific metadata. */
    @Column(name = "metadata", columnDefinition = "JSON", updatable = false)
    private String metadata;

    // ─── Entity Reference ─────────────────────────────────────────────────────

    /** PK of the referenced entity (stagingId, declarationId, documentId, etc.). */
    @Column(name = "reference_id", updatable = false)
    private Long referenceId;

    // ─── Status Transition ────────────────────────────────────────────────────

    @Column(name = "old_status", length = 40, updatable = false)
    private String oldStatus;

    @Column(name = "new_status", length = 40, updatable = false)
    private String newStatus;

    /** WorkflowAction enum name that triggered this event. Null for document events. */
    @Column(name = "workflow_action", length = 40, updatable = false)
    private String workflowAction;

    /**
     * WorkflowTransition.id — UNIQUE constraint enforces idempotency.
     * Null for document events (no workflow transition involved).
     */
    @Column(name = "source_transition_id", unique = true, updatable = false)
    private Long sourceTransitionId;

    // ─── Actor ────────────────────────────────────────────────────────────────

    @Column(name = "performer_id", nullable = false, updatable = false)
    private Long performerId;

    @Column(name = "performer_name", length = 255, updatable = false)
    private String performerName;

    @Column(name = "performer_role", nullable = false, length = 32, updatable = false)
    private String performerRole;

    /** Free-text reason/comment provided at the time of the action. */
    @Column(name = "comment", columnDefinition = "TEXT", updatable = false)
    private String comment;

    /** True when this event was generated by a background job, not a user action. */
    @Builder.Default
    @Column(name = "created_by_system", nullable = false, updatable = false)
    private boolean createdBySystem = false;

    // ─── Timestamp ────────────────────────────────────────────────────────────

    @Column(name = "occurred_at", nullable = false, updatable = false)
    private Instant occurredAt;
}
