-- V3: Temple core and search summary
-- ────────────────────────────────────

CREATE TABLE temples (
    id                       BIGINT        NOT NULL AUTO_INCREMENT,
    name                     VARCHAR(255)  NOT NULL,
    grade                    VARCHAR(2),
    tradition                VARCHAR(32),
    district_id              BIGINT        NOT NULL,
    taluk_id                 BIGINT,
    hobli_id                 BIGINT,
    address_line1            VARCHAR(255),
    address_line2            VARCHAR(255),
    city                     VARCHAR(128),
    pin_code                 VARCHAR(6),
    latitude                 DECIMAL(10,7),
    longitude                DECIMAL(10,7),
    contact_name             VARCHAR(128),
    contact_email            VARCHAR(255),
    contact_phone            VARCHAR(15),
    trust_registered         TINYINT(1)    NOT NULL DEFAULT 0,
    asset_declaration_status VARCHAR(32),
    version                  BIGINT        NOT NULL DEFAULT 0,
    is_deleted               TINYINT(1)    NOT NULL DEFAULT 0,
    created_at               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by               BIGINT,
    updated_by               BIGINT,
    PRIMARY KEY (id),
    INDEX idx_temples_district_id           (district_id),
    INDEX idx_temples_grade                 (grade),
    INDEX idx_temples_tradition             (tradition),
    INDEX idx_temples_trust_registered      (trust_registered),
    INDEX idx_temples_asset_decl_status     (asset_declaration_status),
    INDEX idx_temples_is_deleted            (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE temple_search_summary (
    id                   BIGINT       NOT NULL AUTO_INCREMENT,
    temple_id            BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    grade                VARCHAR(2),
    tradition            VARCHAR(32),
    district_id          BIGINT,
    district_name        VARCHAR(128),
    city                 VARCHAR(128),
    trust_registered     TINYINT(1),
    declaration_status   VARCHAR(32),
    latitude             DECIMAL(10,7),
    longitude            DECIMAL(10,7),
    updated_at           DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tss_temple_id  (temple_id),
    FULLTEXT INDEX ft_tss_name   (name),
    INDEX idx_tss_district_id    (district_id),
    INDEX idx_tss_grade          (grade),
    INDEX idx_tss_tradition      (tradition)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
