-- V73__add_viewer_role.sql
-- Adds the VIEWER role to the system.
--
-- No DDL change required: the 'role' column in the users table uses
-- VARCHAR via @Enumerated(EnumType.STRING). The new 'VIEWER' string value
-- is accepted automatically once the enum is updated in Java.
--
-- This migration is a no-op marker for Flyway versioning. It documents the
-- introduction of the VIEWER role (State Government / Audit Bodies) at this
-- schema version boundary.
--
-- Stakeholder: State Government / Audit Bodies (read-only statewide access)
-- Permissions: CAN_READ_ALL (read), export — zero write surface
-- Jurisdiction: statewide (bypasses district scoping in JurisdictionGuard)
