-- V93: Create temple_timeline_events table
-- Append-only audit trail for every significant temple lifecycle event.
-- Never updated or deleted — immutable once written.

CREATE TABLE IF NOT EXISTS temple_timeline_events (
    id                    BIGINT          NOT NULL AUTO_INCREMENT,
    temple_id             BIGINT          NOT NULL,

    -- Broad event category (WORKFLOW_TRANSITION, DOCUMENT_UPLOAD, DOCUMENT_DELETE, SYSTEM_EVENT)
    event_type            VARCHAR(40)     NOT NULL,

    -- Fine-grained code used for frontend label/icon mapping (e.g. PROFILE_APPROVED)
    event_code            VARCHAR(64)     NOT NULL,

    -- Module context (TEMPLE_PROFILE, DECLARATION, TRUST, BOARD_MEMBER, EMPLOYEE, CONTRACTOR, DOCUMENT)
    module_name           VARCHAR(40),

    -- Human-readable name of the affected entity (e.g. "Trust Deed.pdf", "Declaration FY 2025-26")
    entity_name           VARCHAR(255),

    -- Short human-readable title (denormalized for display without JOINs)
    title                 VARCHAR(255)    NOT NULL,

    -- Longer description / context sentence
    description           TEXT,

    -- Extra JSON metadata (financial year, version number, etc.)
    metadata              JSON,

    -- PK of the referenced entity (stagingId, declarationId, documentId, etc.)
    reference_id          BIGINT,

    -- Status before the event
    old_status            VARCHAR(40),

    -- Status after the event
    new_status            VARCHAR(40),

    -- WorkflowAction enum value that triggered this event (NULL for document events)
    workflow_action       VARCHAR(40),

    -- WorkflowTransition.id — UNIQUE constraint enforces idempotency
    source_transition_id  BIGINT          UNIQUE,

    -- Actor who triggered the event
    performer_id          BIGINT          NOT NULL,
    performer_name        VARCHAR(255),
    performer_role        VARCHAR(32)     NOT NULL,

    -- Optional free-text reason/comment provided at the time of the action
    comment               TEXT,

    -- True when generated by a background job/scheduler (not a user action)
    created_by_system     TINYINT(1)      NOT NULL DEFAULT 0,

    -- Precise timestamp of when the event occurred (not when the row was inserted)
    occurred_at           DATETIME(6)     NOT NULL,

    PRIMARY KEY (id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Primary access pattern: all events for a temple, latest first
CREATE INDEX idx_timeline_temple_occurred
    ON temple_timeline_events (temple_id, occurred_at DESC);

-- Secondary: filter by event type across a temple
CREATE INDEX idx_timeline_event_type
    ON temple_timeline_events (temple_id, event_type);

-- Lookup by source transition (idempotency check)
-- NOTE: the UNIQUE constraint on source_transition_id already creates an index;
--       this named alias index makes explain plans readable.
CREATE INDEX idx_timeline_source_transition
    ON temple_timeline_events (source_transition_id);
