spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    validate-on-migrate: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  aws:
    region: ${AWS_REGION}
    bucket-name: ${AWS_S3_BUCKET}

logging:
  level:
    com.templeregistry: INFO
    org.springframework.security: WARN
