package com.templeregistry.util.pdf;

import com.itextpdf.kernel.events.Event;
import com.itextpdf.kernel.events.IEventHandler;
import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfPage;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.PdfCanvas;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.AreaBreak;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.AreaBreakType;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Template for structured data export reports (Temple lists, Declaration lists).
 *
 * <p>Produces a multi-page, professionally styled PDF report with:
 * <ul>
 *   <li>Government-grade page header with system branding</li>
 *   <li>Summary statistics bar</li>
 *   <li>Styled data table with column headers and alternating row stripes</li>
 *   <li>Page footers with page numbers and system attribution</li>
 * </ul>
 *
 * <p>Usage:
 * <pre>{@code
 *   byte[] pdf = ExportReportTemplate.builder()
 *       .title("Temple Export Report")
 *       .districtLabel("Thanjavur District")
 *       .rows(rows)
 *       .totalCount(rows.size() - 1)
 *       .generatedBy("DC_STAFF / user#42")
 *       .build()
 *       .render();
 * }</pre>
 */
public final class ExportReportTemplate {

    private final String   title;
    private final String   districtLabel;
    private final String   generatedBy;
    private final int      totalCount;
    private final List<String[]> rows;

    private ExportReportTemplate(Builder b) {
        this.title        = b.title;
        this.districtLabel = b.districtLabel;
        this.generatedBy  = b.generatedBy;
        this.totalCount   = b.totalCount;
        this.rows         = b.rows;
    }

    public static Builder builder() { return new Builder(); }

    // ─── Render to byte[] ────────────────────────────────────────────────────

    public byte[] render() {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
            renderTo(bos);
            return bos.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("PDF export report generation failed", e);
        }
    }

    // ─── Render to OutputStream (file-based async export) ───────────────────

    public void renderTo(OutputStream out) throws IOException {
        PdfWriter   pdfWriter = new PdfWriter(out);
        PdfDocument pdfDoc    = new PdfDocument(pdfWriter);

        FooterEventHandler footerHandler = new FooterEventHandler();
        pdfDoc.addEventHandler(PdfDocumentEvent.END_PAGE, footerHandler);

        Document document = new Document(pdfDoc);
        document.setMargins(72f, 36f, 50f, 36f);

        // ── Page header
        String subtitle = buildSubtitle();
        PdfDesignSystem.addPageHeader(document, title, subtitle, generatedBy);

        // ── Summary bar
        String recordCount = String.valueOf(totalCount);
        String reportDate  = LocalDateTime.now().format(PdfDesignSystem.DATE_FORMATTER);
        String district    = PdfDesignSystem.safeStr(districtLabel);

        PdfDesignSystem.addSummaryBar(
            document,
            new String[]{"Total Records", "Report Date", "Jurisdiction"},
            new String[]{recordCount, reportDate, district}
        );

        // ── Data table
        PdfDesignSystem.addSectionDivider(document, "Data Records");
        Table table = PdfDesignSystem.buildDataTable(rows);
        document.add(table);

        // ── Footer note
        Paragraph footerNote = new Paragraph(
            "This report was automatically generated by the Temple Registry Management System. " +
            "Data is accurate as of the generation timestamp. For official use only.")
            .setFont(PdfDesignSystem.fontItalic())
            .setFontSize(PdfDesignSystem.FONT_TINY)
            .setFontColor(PdfDesignSystem.COLOR_TEXT_MUTED)
            .setMarginTop(16f);
        document.add(footerNote);

        document.close();
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private String buildSubtitle() {
        if (districtLabel != null && !districtLabel.isBlank()) {
            return title + " — " + districtLabel;
        }
        return title;
    }

    // ─── Footer Event Handler ─────────────────────────────────────────────────

    private static class FooterEventHandler implements IEventHandler {
        private int pageNumber = 0;

        @Override
        public void handleEvent(Event event) {
            pageNumber++;
            PdfDocumentEvent docEvent = (PdfDocumentEvent) event;
            PdfPage page = docEvent.getPage();
            PdfDocument pdfDoc = docEvent.getDocument();
            PdfCanvas canvas = new PdfCanvas(page, true);
            PdfDesignSystem.renderFooter(canvas, pdfDoc.getDefaultPageSize(), pageNumber);
            canvas.release();
        }
    }

    // ─── Builder ─────────────────────────────────────────────────────────────

    public static final class Builder {
        private String title        = "Export Report";
        private String districtLabel;
        private String generatedBy;
        private int    totalCount;
        private List<String[]> rows = List.of();

        public Builder title(String title)               { this.title = title; return this; }
        public Builder districtLabel(String d)           { this.districtLabel = d; return this; }
        public Builder generatedBy(String g)             { this.generatedBy = g; return this; }
        public Builder totalCount(int count)             { this.totalCount = count; return this; }
        public Builder rows(List<String[]> rows)         { this.rows = rows; return this; }

        public ExportReportTemplate build() { return new ExportReportTemplate(this); }
    }
}
